openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Swagger Petstore"
  description: "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Swagger API Team"
  license:
    name: "MIT"
paths:
  /pets:
    get:
      description: "Returns all pets from the system that the user has access to"
      responses:
        "200":
          description: "A list of pets."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
  /fooBar:
    get:
      description: "Returns all foo bar from the system that the user has access to"
      responses:
        "200":
          description: "A list of foo bars."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FooBarCmp"
    post:
      description: "Returns all foo bar from the system that the user has access to"
      responses:
        "200":
          description: "A list of foo bars."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FooBarCmp"
components:
  schemas:
    Pet:
      type: "object"
      required:
        - "id"
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        tag:
          type: "string"
    FooBarCmp:
      type: "object"
      required:
        - "id"
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        tag:
          type: "string"
